name: App Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        npm install  # Replace with appropriate dependency install command

    - name: Run tests
      run: |
        npm test  # Replace with the appropriate test command for your app

    - name: Simulate failure scenario
      if: github.ref == 'refs/heads/test-failures'
      run: |
        echo "Simulating build failure"
        exit 1

    - name: Simulate syntax error
      if: github.ref == 'refs/heads/test-failures'
      run: |
        bash -c 'echo "Simulating syntax error"; ( syntax error here'
