name: Analyze PR Changes

on:
  push:
    branches:
      - main  # Update to your main branch name

jobs:
  analyze_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Run analysis script
        run: |
          chmod +x analyze_pr_changes.sh
          ./analyze_pr_changes.sh HEAD^ HEAD
