name: Git Operations

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git --version

      - name: Make analyze_pr_changes.sh executable
        run: |
          chmod +x analyze_pr_changes.sh

      - name: Run analyze_pr_changes.sh script
        run: |
          sh ./analyze_pr_changes.sh HEAD^ HEAD
